// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rzljgsegmfbzsjphbppf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ6bGpnc2VnbWZienNqcGhicHBmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxOTYxNjUsImV4cCI6MjA2Mzc3MjE2NX0.c4Pvq10WWJaD2QD6Rpeuf6ciLtEAUwbmRfa25G84m8Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);